account_app/urls.py
from django.contrib import admin
from django.urls import path, include
from account_app import views
from django.conf import settings
from django.conf.urls.static import static
#template tag
app_name = 'account_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('delete_user', views.delete_user, name='delete_user'),
    path('user/<int:user_id>/', views.get_profile, name='get_profile'),
    path('create_group/', views.create_group, name="create_group"),
    path('delete_group/<int:group_id>/', views.delete_group, name="delete_group"),
    path('delete_from_group/<int:group_id>/<int:user_id>', views.delete_user_from_group, name="delete_from_group"),
    path('group/<int:group_id>', views.get_group_page, name='get_group_page'),
    path('abandon_group/<int:group_id>', views.abandon_group, name="abandon_group"),
    path('close_group/<int:group_id>', views.close_group, name="close_group"),


]

coffeeorder_app/urls.py
from django.contrib import admin
from django.urls import path, include
from coffeeorder_app.views import bar_views, order_views, product_views, views

app_name = 'coffeeorder_app'

urlpatterns = [
    path('group/<int:group_id>', views.get_group_page, name='group'),
    path('<int:group_id>/addbar/', bar_views.add_bar, name='add_bar'),
    path('<int:group_id>/menuorderlist/', order_views.menu_order_list, name='menu_order_list'),
    path('<int:group_id>/addorderlist/<int:bar_id>', order_views.add_order_list, name='add_order_list'),
    path('<int:group_id>/deleteorderlist/<int:order_list_id>', order_views.delete_order_list, name='delete_order_list'),
    path('addproduct/', product_views.add_product, name='add_product'),
    path('<int:group_id>/addproductbar/<int:bar_id>', product_views.add_product_bar, name='views.add_product_bar'),
    path('add_order/<int:order_list_id>', order_views.add_order, name='add_order'),
    path('product_to_order/<int:order>/<int:product>/<int:add>', order_views.product_to_order,
         name='product_to_order'),


    path('checkorder', order_views.check_order, name="check_order"),
]

coffeeorder_app/forms/bar_forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from coffeeorder_app.model.bar import Bar
from coffeeorder_app.model.product import Product, ProductVariation


class AddBarForm(forms.ModelForm):

    class Meta:
        model = Bar
        msg_required = "Obligatory field"

        fields = (
            'bar_name',
            'bar_description',
            'bar_color',
        )

        fields_required = (
            'bar_name',
        )
        labels = {
            'bar_name': _("Bar's Name"),
            'bar_description': _("Description of the bar"),
            'bar_color': _("Bar card color"),
        }
        error_messages = {
            'bar_name': {
                'required': _(msg_required)
            }
        }
        widgets = {
            'bar_name': forms.TextInput(attrs={'class': 'form-control', }),
            'bar_description': forms.TextInput(attrs={'class': 'form-control', }),
            'bar_color': forms.TextInput(attrs={'class': 'form-control  color-menu', }),
        }

coffeeorder_app/forms/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from coffeeorder_app.model.bar import Bar
from coffeeorder_app.model.product import Product, ProductVariation







'''
class AddProductBarForm(forms.ModelForm):

    class Meta:
        model = ProductVariation

        msg_required = "Campo obligatorio"

        fields = (
            'product_variation_name',
        )
        fields_required = (

        )

        labels = {
            'product_variation_name': _('Variación del producto(TIPO)'),
        }
        error_messages = {
            'product_variation_name': {
                'required': _(msg_required)
            }
        }
        widgets = {
            'product_variation_name': forms.TextInput(attrs={'class': 'form-control', }),
        }
'''

coffeeorder_app/forms/order_forms.py
from django import forms
from django.core import validators
from django.utils.translation import gettext as _
from coffeeorder_app.model.bar import Bar
from coffeeorder_app.model.product import Product, ProductBar
from coffeeorder_app.model.order import Order,OrderList
msg_required = "Obligatory field"


class SingleOrder(forms.Form):

    class Meta:
        fields = (
            'product_name',
            'product_color',
            'product_type',
        )

        fields_required = (
            'product_name',
            'product_type',
        )
        labels = {
            'product_name': _('Name'),
            'product_type': _('Type of product'),
            'product_color': _('Color'),
        }
        help_texts = {
            'product_color': _('Choose the color for the card of the product')
        }
        error_messages = {
            'product_name': {
                'required': _(msg_required)
            }
        }
        widgets = {
            'product_name': forms.TextInput(attrs={'class': 'form-control', }),

            'product_color': forms.TextInput(attrs={'class': 'form-control  color-menu', }),
        }

#class selectProductForm(forms.Form):
 #       product = none

coffeeorder_app/views/bar_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect

from coffeeorder_app.forms.bar_forms import AddBarForm

from ..model.bar import Bar
from account_app.models import UserGroup



@login_required
def add_bar(request, group_id):
    registered = False
    if request.method == "POST":
        bar_form = AddBarForm(request.POST)
        if bar_form.is_valid():
            group = UserGroup.objects.get(id=group_id)
            bar = bar_form.save()
            bar.group.add(group)
            bar_form.save()
            registered = True
            return redirect('index')
        else:
            print(bar_form.errors)
    else:
        bar_form = AddBarForm()
    return render(request, 'coffeeorder_app/addBar.html', {'bar_form': bar_form, 'registered': registered})


@login_required
def get_bar(request, bar_id):
    bar = Bar.objects.get(id=bar_id)
    return bar


@login_required
def delete_bar(request, bar_id):
    if Bar.objects.get(id=bar_id).delete():
        Bar.objects.get(id=bar_id).delete()
        return True
    else:
        return False


@login_required
def modify_bar(request, bar_id):
    bar = Bar.objects.get(id=bar_id)
    pass

coffeeorder_app/views/order_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect


from datetime import datetime, timedelta
from django.http import JsonResponse
from ..model.order import OrderList, Order, OrderItem
from ..model.bar import Bar
from ..model.product import ProductBar, Product
from account_app.models import UserGroup
from django.db.models import Q


@login_required
def menu_order_list(request, group_id):
    group = UserGroup.objects.get(id=group_id)
    official_bar = Bar.objects.filter(bar_official=True)
    group_bars = Bar.objects.filter(group=group)
    return render(request, 'coffeeorder_app/menuOrderList.html', {'group': group,
                                                                  'official_bar': official_bar,
                                                                  'group_bars': group_bars})


@login_required
def add_order_list(request, group_id, bar_id):
    bar = Bar.objects.get(id=bar_id)
    group = UserGroup.objects.get(id=group_id)
    orders = OrderList.objects.filter(order_group=group, state=True)

    free = True

    for order in orders:
        print(orders)
        if bar == order.order_bar and group == order.order_group:
            free = False
            break
    #free = True
    if free:
        order_list = OrderList()
        time_created = datetime.today()
        time_expiration = time_created + timedelta(hours=2)
        order_list.created = time_created
        order_list.user_creator = request.user
        order_list.expiration = time_expiration
        order_list.order_bar = bar
        order_list.order_group = group
        order_list.save()

    response = '/coffeeorder_app/group/{}'.format(group_id)
    return redirect(response)


@login_required
def delete_order_list(request, group_id, order_list_id):
    order_list = OrderList.objects.get(id=order_list_id)
    order_list.state = False
    order_list.save()
    return redirect('coffeeorder_app:group', group_id=group_id)


@login_required
def modify_order_list(request, order_list_id):
    order = Order.objects.get(id=order_list_id)
    pass


@login_required
def check_order(request):
    today = datetime.today()
    orders = OrderList.objects.filter(Q(expiration__lte=today))

    for order in orders:

        #order.state = False
        order.delete()

    return redirect('index')


@login_required
def order_ticket(request, order_list_id, individual=False):
    order_list = OrderList.objects.get(pk=order_list_id)
    order_details = {}
    order_prize = 0
    if individual:
        try:
            order = Order.objects.get(order_order_list_id=order_list.id, order_user=request.user)
            products = OrderItem.objects.filter(order=order)
            for prod in products.all():
                try:
                    prize = prod.order_product_bar.product_bar_prize * int(prod.quantity)
                    order_details[prod.order_product_bar.product.product_name] = {
                        'quantity': prod.quantity,
                        'prize': prize,
                        'product_id': prod.order_product_bar.id,
                    }
                    order_prize += prize
                except OrderItem.DoesNotExist:
                    order_details[prod.order_product_bar.product.product_name] = {
                        'quantity': 0,
                        'prize': 0,
                        'product_id': prod.order_product_bar.id,
                    }
        except Order.DoesNotExist:
            pass
    else:
        orders = Order.objects.filter(order_order_list_id=order_list.id)
        for single in orders:
            order_details[single.order_user.username] = {}

            products = OrderItem.objects.filter(order=single)
            for prod in products.all():
                try:
                    prize = prod.order_product_bar.product_bar_prize * int(prod.quantity)
                    order_details[single.order_user.username][prod.order_product_bar.product.product_name] = {
                        'quantity': prod.quantity,
                        'prize': prize,
                        'product_id': prod.order_product_bar.id,
                    }
                    order_prize += prize
                except OrderItem.DoesNotExist:
                    order_details[single.order_user.username][prod.order_product_bar.product.product_name] = {
                    'quantity': 0,
                    'prize': 0,
                    'product_id': prod.order_product_bar.id,
                }

    return order_details, order_prize

@login_required
def product_to_order(request, order, product, add=2):

    try:
        item = OrderItem.objects.get(order_product_bar_id=product,
                                     order_id=order)
    except OrderItem.DoesNotExist:

        order_target = Order.objects.get(pk=order)
        order_product = ProductBar.objects.get(pk=product)
        item = OrderItem.objects.create(order=order_target,
                                        order_product_bar=order_product,
                                        quantity=0)
        item.save()

    if add == 0 and item.quantity > 0:
        item.quantity -= 1
    elif add == 1:
        item.quantity += 1

    if item.quantity == 0 or add == 2:
        item.delete()
    else:
        item.save()

    list_id = Order.objects.get(pk=order).order_order_list.pk
    order_details, order_prize = order_ticket(request, list_id, True)

    data = {
        'order_details': order_details,
        'prize': order_prize
    }
    return JsonResponse(data)


def add_order(request, order_list_id):
    order_list = OrderList.objects.get(pk=order_list_id)

    bar = Bar.objects.get(bar_name=order_list.order_bar.bar_name)
    products_bar = ProductBar.objects.filter(product_bar_bar=bar.id)
    food_list, drink_list = [], []
    try:
        order = Order.objects.get(order_order_list_id=order_list.id,
                                  order_user=request.user)

    except Order.DoesNotExist:
        '''no order found'''
        order = Order.objects.create(order_order_list_id=order_list.id,
                                  order_user=request.user)
    except Order.MultipleObjectsReturned:
        '''multiples orders'''

    order_details, order_prize = order_ticket(request, order_list_id, True)
    for product in products_bar:
        product_ins = Product.objects.get(id=product.product.id)
        if product_ins.product_type is '0':
            food_list.append({'product_id': product.id,
                              'name': product_ins.product_name,
                              'prize': product.product_bar_prize,
                              'color': product_ins.product_color})
        else:
            drink_list.append({
                'product_id': product.id,
                'name': product_ins.product_name,
                'prize': product.product_bar_prize,
                'color': product_ins.product_color})
    return render(request, 'coffeeorder_app/addOrder.html',
                  {'food_list': food_list,
                   'drink_list': drink_list,
                   'order_details': order_details,
                   'order_prize': order_prize,
                   'order_id': order.id}
                  )


def update_order(request):
    order_updated = {}
    return order_updated


@login_required
def get_order(request, order_id):
    order = Order.objects.get(id=order_id)
    pass


@login_required
def modify_order(request, order_id):
    order = Order.objects.get(id=order_id)
    pass


@login_required
def delete_order(request, order_id):
    order = Order.objects.get(id=order_id)
    pass

coffeeorder_app/views/product_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
# 3rd

from coffeeorder_app.forms.product_forms import AddProductForm

from ..model.product import Product


@login_required
def get_product(request, product_id):
    product = Product.objects.get(id=product_id)
    pass


@login_required
def get_product_variation(request, product_variation_id):
    pass


@login_required
def add_product(request):

    if request.method == "POST":
        product_form = AddProductForm(request.POST)

        if product_form.is_valid():
            product_form.save()
            return redirect('coffeeorder_app:add_product')
        else:
            print(product_form.errors)
    else:
        product_form = AddProductForm()

    return render(request, 'coffeeorder_app/addProduct.html', {
        'product_form': product_form,

    })


@login_required
def add_product_bar(request,bar_id, product_id):
    return render(request, 'coffeeorder_app/addProductBar.html',)



@login_required
def delete_product(request, product_id):
    pass


@login_required
def delete_product_variation(request, product_variation_id):
    pass


@login_required
def update_product(request, product_id):
    pass


@login_required
def update_product_variation(request, product_variation_id):
    pass

coffeeorder_app/templates/coffeeorder_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html  lang="es">
<head>
    <title>{% block title %}COFFEEORDER APP!{% endblock title %}</title>
    {% block favicon %}
        <link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}" type="image/gif" sizes="16x16">
        <link rel="icon" href="{% static 'favicon/favicon.ico' %}" type="image/x-icon"/>
        <link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}" type="image/x-icon"/>
    {% endblock favicon %}
    {% block head %}
        {% block head_charset %}
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        {% endblock head_charset %}
        {% block metas %}
          <meta name="description" content="Coffe order application">
          <meta name="keywords" content="COFFEE,Coffee,Coffe,Cofee,Cofe, order,list,bar,coffeeshop">
          <meta name="author" content="Arturo OG">
        {% endblock metas %}
        {% block head_contentlanguage %}
            <meta http-equiv="Content-Language" value="es"/>
        {% endblock head_contentlanguage %}
        {% block header_javascript_site %}
            <script src="{% static 'js/jquery.min.js' %}"></script>
            <script src="{% static 'js/bootstrap.min.js' %}"></script>
            <script src="{% static 'js/main.js' %}"></script>
            <script>
                $(document).ready(function () {
                    // get current URL path and assign 'active' class
                    var pathname = window.location.pathname;
                    $('.nav > li > a[href="' + pathname + '"]').parent().addClass('active');
                });
            </script>
        {% endblock header_javascript_site %}
        {% block head_viewport %}
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% endblock head_viewport %}
    {% endblock head %}
    {% block head_css %}
        {% block head_css_site %}
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
            <link href="{% static 'css/basic.css' %}" rel="stylesheet" media="screen">
            <link href="{% static 'css/coffee-icon.css' %}" rel="stylesheet" media="screen">
            <link href="{% static 'css/coffee.css' %}" rel="stylesheet" media="screen">
        {% endblock head_css_site %}
        {% block head_css_section %}{% endblock head_css_section %}
        {% block head_css_page %}{% endblock head_css_page %}
    {% endblock head_css %}
</head>

<body>
{# Navigation #}
<header>
    {% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-light ">
        <a class="navbar-brand" href="{% url 'index' %}">
            <div class="figure col-12">
                <img class="brand-logo" src="{% static 'images/svgs/1coffee.svg' %}"/>
                <span>COFFEEORDER</span>
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle  active" data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false">
                            <img class="avatar-img-nav"
                                 src="{% static 'images/profile_pics/' %}{{ request.user.profile_pic }}">
                        {{ request.user.username }}
                        <span class="caret"></span></a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'account_app:get_profile' user.id %}">Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'account_app:user_logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    {% endif %}
    </nav>
</header>

{# The Document Body #}
<div class="content-container">
    {% block content %}
    {% endblock content %}
</div>
{# Footer #}
{% if user.is_authenticated %}

{% endif %}
</body>

{# JavaScript #}
{% block footer_javascript %}
    {% block footer_javascript_site %}
    {% endblock footer_javascript_site %}
    {% block footer_javascript_section %}{% endblock footer_javascript_section %}
    {% block footer_javascript_page %}{% endblock footer_javascript_page %}
{% endblock footer_javascript %}
</html>

coffeeorder_app/templates/coffeeorder_app/groupPage.html
{% extends "coffeeorder_app/base.html" %}
{% load staticfiles %}
{% block head_css_page %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet" media="screen">
{% endblock head_css_page %}
{% block content %}

    <div class="jumbotron text-center">
        {% if user.is_authenticated and group %}
            <div class="row">
                <h1 class="mx-auto">GROUP: {{ group.group_name|default:' ' }}</h1>
            </div>
            <div class="row">
                <a role="button" class="btn btn-primary"
                   href="{% url 'coffeeorder_app:menu_order_list' group.id %}"><span
                        class="glyphicon glyphicon-plus-sign"></span> CREATE ORDER</a>
                <a role="button" class="btn btn-primary disabled" hidden href="{% url 'coffeeorder_app:add_bar' group.id %}"><span
                        class="glyphicon glyphicon-plus-sign  disabled" hidden ></span> CREATE BAR</a>
                <a role="button" class="btn btn-primary" id="inviteToGroup" onclick="show_code()"><span
                        class="glyphicon glyphicon-plus-sign"></span> INVITE TO GROUP</a>
            </div>
            <div class="row group-options">
                <a role="button" class="btn btn-danger" href="{% url 'account_app:abandon_group' group.id %}">
                    ABANDON GROUP
                </a>
                {% if admin %}
                    <a role="button" class="btn btn-danger"
                       href="{% url 'account_app:delete_group' group.id %}">DELETE GROUP</a>
                    <a role="button" id="close_button" class="btn btn-warning" onclick="close_group_button()">
                        {% if group.closed %}OPEN{% else %}CLOSE{% endif %} GROUP</a>
                {% endif %}
            </div>
            <div class="row " id="invitationContainer">
                <div class="col-md-4 col-sm-12 col-md-offset-4 hidden-box">
                    <h3>INVITATION CODE:</h3>
                    <h2 style="color: red;font-weight: bold">{{ group.group_code }}</h2>
                </div>
            </div>
        {% else %}
            <p> This group does not exist anymore or you are not a member of it.</p>
        {% endif %}
    </div>

    {% include "coffeeorder_app/orderContainer.html" %}
    {% include "coffeeorder_app/memberContainer.html" %}

    {% block footer_javascript_page %}
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/coffee.js' %}"></script>
        <script>
            function close_group_button() {
                $.ajax({
                    url: "{% url 'account_app:close_group' group.id %}",

                    dataType: 'json',
                    success: function (data) {
                        if (data.is_closed) {
                            $("#close_button").text("OPEN GROUP")

                        } else {
                            $("#close_button").text("CLOSE GROUP")
                        }
                    }
                });
            };
        </script>
    {% endblock footer_javascript_page %}
{% endblock %}

coffeeorder_app/templates/coffeeorder_app/memberContainer.html
{% load staticfiles %}
<div class="container-fluid ">
    {% if user.is_authenticated and group %}
        <div class="card-container">
            <div class="row">
                <div class="col-12"><h1> MEMBERS</h1></div>
                {% for key,member in members.items %}
                    <div  class="col-12 col-md-3 col-lg-3 mt-4 ">
                        <div class="card">
                            <img class="card-img-top"
                                 src="{% static 'images/profile_pics/' %}{{ member.profile_pic }}">
                            <div class="card-block">
                                <h4 class="card-title mt-3">{{ member.username }}</h4>
                            </div>
                            {% if admin and key != request.user.id %}
                                <div class="card-footer">
                                    <a class="btn  float-right btn-sm btn-danger"
                                       href="{% url 'account_app:delete_from_group' group.id key %}">REMOVE</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div> <!-- row -->
        {% else %}
            <a type="button" class="btn btn-lg btn-default" href="#"><span
                    class="glyphicon glyphicon-plus-sign"></span> Create group</a>
        {% endif %}
    </div> <!-- card-container-->
</div> <!-- container-->

coffeeorder_app/templates/coffeeorder_app/menuOrderList.html
{% extends "coffeeorder_app/base.html" %}
{% load staticfiles %}
{% block head_css_section %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet" media="screen">
{% endblock head_css_section %}
{% block content %}

    <div class="jumbotron text-center">

        <h1>Create new order list</h1>

    </div>
    <a role="button" class="btn btn-primary" href="{% url 'coffeeorder_app:add_bar' group.id %}"><span
            class="glyphicon glyphicon-plus-sign"></span> ADD BAR</a>

    <div id="listmenu" class="container-fluid">
        <div class="row">
            <h2>Select a bar:</h2>
        </div>
        <div class="card-container">
            <div class="row">
                <div class="col-12"><h1> OFFICIALS:</h1></div>
                {% for bar in official_bar.all %}
                    <div class="col-12 col-md-3 col-lg-3 mt-4 ">
                        <a href="{% url 'coffeeorder_app:add_order_list' group.id bar.id %}">
                            <div class="card">
                                <div class="card-block" style="background-color:{{ bar.bar_color }};">
                                    <h4 class="card-title mt-3">{{ bar.bar_name }}</h4>
                                    <p class="card-text">{{ bar.bar_info }}</p>
                                </div>
                                <div class="card-footer">
                                    <img class="card-logo" src="/static/images/svgs/1coffee.svg">
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-12"><h1> UNOFFICIALS:</h1></div>
                {% for bar in group_bars.all %}
                    <div class="col-12 col-md-3 col-lg-3 mt-4 ">
                        <a href="{% url 'coffeeorder_app:add_order_list' group.id bar.id %}">
                            <div class="card">
                                <div class="card-block" style="background-color:{{ bar.bar_color }};">
                                    <h4 class="card-title mt-3">{{ bar.bar_name }}</h4>
                                    <p class="card-text">{{ bar.bar_info }}</p>
                                </div>
                                <div class="card-footer">
                                    <img class="card-logo" src="/static/images/svgs/1coffee.svg">
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div> <!-- card-container -->
    </div> <!-- container-->
{% endblock %}
{% block footer_javascript_page %}
{% endblock footer_javascript_page %}

coffeeorder_app/templates/coffeeorder_app/orderContainer.html
{% if order_list_details %}
    <div class="container-fluid">
        <div class="card-container ">
            <div class="row"><h2>LIST OF ACTIVE ORDERS</h2></div>
            <div class="row">
                {% for key,value in order_list_details.items %}

                    <div class="col-12 col-md-6  col-lg-3 mt-4">
                        <div class="card">
                            <div class="card-block" style="background-color:{{ bar.bar_color }};">
                                <h2 class="card-title mt-3">BAR:{{ value.order.order_bar.bar_name| default:"" }}</h2>
                                <h2 class="card-title mt-3">GROUP:{{ value.order.order_group.group_name }}</h2>
                                <p class="card-text">{{ value.order.created }}</p>
                                {% for user, products in value.details.items  %}
                                    {% for product, p_detail in products.items%}
                                    <div class="row" id="{{ product }}-{{ det.product_id }}">
                                        <div class="col-12">
                                            <span id="{{ product }}-{{  p_detail.product_id }}-product">{{ product }}</span> X
                                            <span id="{{ product }}-{{  p_detail.product_id }}-quantity">{{ p_detail.quantity }}</span> =>
                                            <span id="{{ product }}-{{  p_detail.product_id }}-prize">{{  p_detail.prize }}</span>€
                                            (<span id="{{ product }}-{{  p_detail.product_id }}-user">{{  user }}</span>)
                                        </div>
                                    </div>
                                     {% endfor %}
                                {% endfor %}
                                <hr>
                                <a class="btn  btn-warning" href="{% url 'coffeeorder_app:add_order'  key %}">MAKE
                                    ORDER!</a>
                                <p class="card-text card-prize">{{  value.prize|default:0 }}€</p>
                            </div>
                            <div class="card-footer">
                                {% if admin %}
                                    <a class="btn  float-right btn-sm btn-danger"
                                       href="{% url 'coffeeorder_app:delete_order_list' group.id key %}">DELETE</a>
                                {% else %}
                                    <img class="card-logo" src="/static/images/svgs/1coffee.svg">
                                {% endif %}
                            </div>
                        </div>

                    </div>
                {% endfor %}
            </div>
        </div> <!-- card-container -->
    </div> <!-- container-->
{% endif %}