account_app/urls.py
from django.contrib import admin
from django.urls import path, include
from account_app import views
from django.conf import settings
from django.conf.urls.static import static
#template tag
app_name = 'account_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('delete_user', views.delete_user, name='delete_user'),
    path('user/<int:user_id>/', views.get_profile, name='get_profile'),
    path('create_group/', views.create_group, name="create_group"),
    path('delete_group/<int:group_id>/', views.delete_group, name="delete_group"),
    path('delete_from_group/<int:group_id>/<int:user_id>', views.delete_user_from_group, name="delete_from_group"),
    path('group/<int:group_id>', views.get_group_page, name='get_group_page'),
    path('abandon_group/<int:group_id>', views.abandon_group, name="abandon_group"),
    path('close_group/<int:group_id>', views.close_group, name="close_group"),


]

coffeeorder_app/urls.py
from django.contrib import admin
from django.urls import path, include
from coffeeorder_app.views import bar_views, order_views, product_views, views

app_name = 'coffeeorder_app'

urlpatterns = [
    path('group/<int:group_id>', views.get_group_page, name='group'),
    path('<int:group_id>/addbar/', bar_views.add_bar, name='add_bar'),
    path('<int:group_id>/menuorderlist/', order_views.menu_order_list, name='menu_order_list'),
    path('<int:group_id>/addorderlist/<int:bar_id>', order_views.add_order_list, name='add_order_list'),
    path('<int:group_id>/deleteorderlist/<int:order_list_id>', order_views.delete_order_list, name='delete_order_list'),
    path('addproduct/', product_views.add_product, name='add_product'),
    path('<int:group_id>/addproductbar/<int:bar_id>', product_views.add_product_bar, name='views.add_product_bar'),
    path('add_order/<int:order_list_id>', order_views.add_order, name='add_order'),
    path('product_to_order/<int:order>/<int:product>/<int:add>', order_views.product_to_order,
         name='product_to_order'),


    path('checkorder', order_views.check_order, name="check_order"),
]

account_app/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.conf import settings


# Create your model here.
PROFILE_PIC_CHOICES = (
    ('256_0.png', '0'),
    ('256_1.png', '1'),
    ('256_2.png', '2'),
    ('256_3.png', '3'),
    ('256_4.png', '4'),
    ('256_5.png', '5'),
    ('256_6.png', '6'),
    ('256_7.png', '7'),
    ('256_8.png', '8'),
    ('256_9.png', '9'),
    ('256_10.png', '10'),
    ('256_11.png', '11'),
    ('256_12.png', '12'),
    ('256_13.png', '13'),
    ('256_14.png', '14'),
    ('256_15.png', '15'),
    ('256_16.png', '16'),
)


class CustomUser(AbstractUser):
    # add additional fields in here
    profile_pic = models.CharField(choices=PROFILE_PIC_CHOICES, default='256_0.png', max_length=100)


class UserGroup(models.Model):

    group_name = models.CharField(max_length=100, unique=True)
    group_description = models.TextField(max_length=220, blank=True)
    max_members = models.IntegerField(default=15)
    group_color = models.CharField(max_length=100, default="yellow")
    group_code = models.CharField(max_length=100)
    closed = models.BooleanField(default=False)

    group_admin = models.ManyToManyField(CustomUser, related_name='groupAdmin')
    group_members = models.ManyToManyField(CustomUser, related_name='groupMembers')

    def __str__(self):
        return self.group_name

account_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import gettext as _
from .models import UserGroup, CustomUser
from django.core.files.images import get_image_dimensions


class CustomUserCreationForm(UserCreationForm):
    """ Clase formulario para datos de usuarios basicos"""
    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', }))

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in [ 'password1', 'password2']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].widget = forms.PasswordInput(attrs={'class': 'form-control', })

    class Meta(UserCreationForm):
        model = CustomUser
        msg_required = "Obligatory field"
        fields = (
            'username',
            'first_name',
            'email',
            'password1',
            'password2',
            'profile_pic',
        )
        fields_required = (
            'username',
            'email',
            'password1',
            'password2',
        )

        labels = {
            'username': _('UserName'),
            'first_name': _('Name'),
            'email': _('Email:'),
            'profile_pic': _('Profile avatar:'),
        }
        help_texts = {
            'first_name': _('Not obligatory, just to identify easily the user'),
            'password1': _('not needed'),
            'password2': "SS",
        }
        error_messages = {
            'username': {
                'max_length': _("Length not valid"),
                'required': _(msg_required)
            },

            'email': {
                'required': _(msg_required)
            },
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', }),
            'first_name': forms.TextInput(attrs={'class': 'form-control', }),
            'email': forms.EmailInput(attrs={'class': 'form-control', }),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', }),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', }),
        }


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name')


class UserForm(forms.ModelForm):
    """ Clase formulario para datos de usuarios basicos"""
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control ', }))

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            msg = "Passwords do not match"
            self.add_error('password', msg)

    class Meta:
        model = User
        msg_required = "Obligatory field"
        fields = (
        'username',
        'first_name',
        'email',
        'password',
        'confirm_password'
        )
        fields_required= (
            'username',
            'email',
            'password',
            'confirm_password'
            )

        labels = {
            'username': _('UserName'),
            'first_name': _('Name'),
            'email': _('Email:'),
            'password':  _('Password :'),
            'confirm_password':    _('Confirm password:'),
        }
        help_texts = {
            'first_name': _('Not obligatory, just to identify easily the user'),
        }
        error_messages = {
            'username': {
                'max_length': _("Length not valid"),
                'required': _(msg_required)
            },
            'password': {
                'required': _(msg_required)
            },
            'confirm_password': {
                'required': _(msg_required)
            },
            'email': {
                'required': _(msg_required)
            },
        }
        widgets = {
                    'username': forms.TextInput(attrs={'class': 'form-control',}),
                    'first_name': forms.TextInput(attrs={'class': 'form-control',}),
                    'email': forms.EmailInput(attrs={'class': 'form-control',}),
                }

'''
class UserProfileForm(forms.ModelForm):
    """ Clase formulario detalles adicionales sobre el usuario"""

    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic',)
        labels = {
                'profile_pic': _('Profile avatar:'),
                }
        help_texts = {
        }
        widgets = {
        }
'''

class GroupForm(forms.ModelForm):
    """ FORMULARIO PARA CREAR GRUPOS"""

    class Meta:
        model = UserGroup
        fields = ('group_name', 'group_description', 'max_members', 'group_color', )
        labels = {
                'group_name': _('Name of the group'),
                'group_description': _('Describe  the group'),
                'max_members': _('Max number of members'),
                'group_color': _('Group color'),
                }
        help_texts = {

        }
        widgets = {
            'group_name': forms.TextInput(attrs={'class': 'form-control', }),
            'group_description': forms.TextInput(attrs={'class': 'form-control', }),
            'max_members': forms.NumberInput(attrs={'class': 'form-control', }),
            'group_color':  forms.TextInput(attrs={'class': 'form-control color-menu', }),
        }
class JoinGroupForm(forms.Form):
    """ FORMULARIO PARA CREAR GRUPOS"""

    group_code = forms.CharField(label='Invitation code', widget=forms.TextInput(attrs={'required': 'required', 'class': 'form-control', }))

    def clean(self):
        all_clean_data = super( JoinGroupForm, self).clean()
        group_code = all_clean_data['group_code']

account_app/views.py
from django.shortcuts import render
from . import forms
from django.utils.translation import gettext as _
#
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse

from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime

from .forms import CustomUserCreationForm, GroupForm
from .models import CustomUser, UserGroup
from coffeeorder_app.model.order import OrderList
from django.contrib.auth.models import User
import random, string
from .decorators import is_group_admin
app_name = 'account_app'
# Create your views here.




# #################USER##################

def is_admin(group_id,user_id):
    group = UserGroup.objects.get(id=group_id)

    if group.group_admin.filter(pk=user_id).exists():
        return True
    else:
        return False

def register(request):
    registered = False
    if request.method == "POST":
        #user_form = UserForm(data=request.POST)
        user_form = CustomUserCreationForm(request.POST, request.FILES)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True

            return redirect('index')
        else:
            print(user_form.errors)
            return render(request, '{}/registration.html'.format(app_name),
                          {'user_form': user_form,
                           'registered': registered})
    else:
        user_form = CustomUserCreationForm()
        return render(request,'{}/registration.html'.format(app_name),
        {'user_form': user_form,
        'registered': registered})


#LOGIN
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect('index')

            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed")
            print("Username: {} ".format(username))
            return render(request, '{}/login.html'.format(app_name), {'login_error':'Credeenciales no válidos'})
    else:
        return render(request, '{}/login.html'.format(app_name), {})


# LOGOUT
@login_required
def user_logout(request):
    logout(request)
    return redirect('index')


@login_required
def delete_user(request):
    from django.contrib.auth.models import User

    user = CustomUser.objects.get(username=request.user.username)
    groups = UserGroup.objects.filter(group_admin=user)
    for group in groups:

        if group.group_members.count() == 1:
            delete_group(group.id)
    user.delete()
    logout(request)
    return redirect('index')


@login_required
def delete_user_from_group(request, group_id, user_id):
    from django.contrib.auth.models import User
    group = UserGroup.objects.get(id=group_id)
    user_to_delete = CustomUser.objects.get(id=user_id)
    if group.group_admin.filter(pk=request.user.pk).exists():
        group.group_admin.remove(user_to_delete)
        group.group_members.remove(user_to_delete)
    response = '/account_app/group/{}'.format(group.id)
    return redirect(response)


# ###########ENDUSER###########################
# ##########group###############

@login_required
def delete_group(request, group_id):

    group_to_delete = UserGroup.objects.get(id=group_id)
    if is_admin(group_id, request.user.id):
        group_to_delete.delete()

    return redirect('index')


@login_required
def abandon_group(request, group_id):
    print("xxxABANDONING")
    group_to_abandon = UserGroup.objects.get(id=group_id)
    group_to_abandon.group_members.remove(request.user)
    print("ABANDONING")
    if group_to_abandon.group_members.count() == 0:
        print("GRUPO VACIO")
        delete_group(request, group_id)

    return redirect('index')


@login_required
def get_profile(request, user_id):
    user = CustomUser.objects.get(id=user_id)

    groups_in = UserGroup.objects.filter(group_members=user).values()
    user_data = {
        'user': user,
        'groups_in': groups_in,
    }

    return render(request, '{}/userProfile.html'.format(app_name), {'user_data': user_data})


@login_required
def create_group(request):
    registered = False
    if request.method == "POST":
        group_form = GroupForm(request.POST, request.FILES)
        if group_form.is_valid():
            group = group_form.save()
            group.group_code = ''.join(random.choices(string.ascii_letters + string.digits, k=4)).upper()
            group.group_admin.add(request.user)
            group.group_members.add(request.user)
            group.save()
            registered = True
            return redirect('index')
        else:
            print(group_form.errors)
    else:
        group_form = GroupForm()
    return render(request, '{}/creategroup.html'.format(app_name), {'group_form': group_form, 'registered': registered})


@login_required
def get_group_page(request, group_id):
    group = UserGroup.objects.get(id=group_id)
    members = {}

    for g in group.group_members.all():

        user = CustomUser.objects.get(id=g.id)
        members[g.id] = {
            'username': g.username,
            'name': g.first_name,
            'profile_pic': g.profile_pic,
        }
        order_list = OrderList.objects.filter(order_group=group)

    if group.group_members.filter(pk=request.user.pk).exists():

        if is_admin(group_id, request.user.id):
            admin = True
        else:
            print('NO ES ADMIN...')
            admin = False
        return render(request, 'coffeeorder_app/groupPage.html',{
            'group': group,
            'members': members,
            'admin': admin,
            'order_list': order_list,

        })
    else:
        return render(request, 'coffeeorder_app/groupPage.html' )


@login_required
def close_group(request, group_id):
    group = UserGroup.objects.get(id=group_id)
    if is_admin(group_id, request.user.id):
        if group.closed:
            print("IS OPEN")
            group.closed = False
            group.save()
        else:
            print("IS NO OPEN")
            group.closed = True
            print(group.closed)
            group.save()
    data = {
        'is_closed': group.closed
    }
    return JsonResponse(data)
# ##########END GROUP###################

account_app/templates/account_app/creategroup.html
{% extends "coffeeorder_app/base.html" %}
{% load staticfiles %}
{% block head_css_section %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet" media="screen">
{% endblock head_css_section %}
{% block content %}
    <script src="{% static 'js/piklor.min.js' %}"></script>
    <div class="jumbotron text-center">
        {% if registered %}
            <h1>Group created!</h1>
        {% else %}
            <h1>CREATE NEW GROUP</h1>
        {% endif %}
    </div>

    {% if registered == False %}

        <div class="container-fluid ">
            <div class="container-fluid registration-container col-md-6 col-md-offset-3">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <h2>Info of the group:</h2>
                        <form enctype="multipart/form-data" method="post">
                            {% csrf_token %}
                            {% for field in group_form %}
                                <div class="form-group">
                                    <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p>{{ field.errors }}{{ forms.non_field_errors }}</p>
                                    {% if field.help_text %}
                                        <small class="form-text text-muted">{{ field.help_text }}</small>
                                    {% endif %}
                                </div>
                            {% endfor %}
                            <div class="text-center">
                                <input class="btn btn-primary" type="submit" name="" value="CREATE GROUP"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <a role="button" class="btn btn-primary" style='margin: 5% 50%;' href="{% url 'index' %}">HOME</a>
    {% endif %}
{% endblock %}
{% block footer_javascript_page %}
    <script>
        var colorElement = " <div class='picker-wrapper'> \
            <a role='button' class='btn btn-success'>Seleccione un color</a> \
            <div class='color-picker'> \
                    </div> \
                </div> "
        $(".color-menu").before(colorElement);
        console.log("S")
        window.addEventListener("load", function () {
            var pk = new Piklor(".color-picker", [
                    "#1abc9c"
                    , "#2ecc71"
                    , "#3498db"
                    , "#9b59b6"
                    , "#34495e"
                    , "#16a085"
                    , "#27ae60"
                    , "#2980b9"
                    , "#8e44ad"
                    , "#2c3e50"
                    , "#f1c40f"
                    , "#e67e22"
                    , "#e74c3c"
                    , "#ecf0f1"
                    , "#95a5a6"
                    , "#f39c12"
                    , "#d35400"
                    , "#c0392b"
                    , "#bdc3c7"
                    , "#7f8c8d"
                ], {
                    open: ".picker-wrapper .btn"
                })
                , wrapperEl = pk.getElm(".picker-wrapper ")
                , header = pk.getElm("header")
                , footer = pk.getElm("footer")
            ;

            pk.colorChosen(function (col) {
                $("#id_group_color").val(col)
                wrapperEl.style.backgroundColor = col;

            });
        });
    </script>
{% endblock footer_javascript_page %}

account_app/templates/account_app/groupProfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

account_app/templates/account_app/groupView.html
{% extends "coffeeorder_app/base.html" %}
{% load staticfiles %}
{% block head_css_page %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet" media="screen">
{% endblock head_css_page %}
{% block content %}

    <div class="jumbotron text-center">
        {% if user.is_authenticated and group %}
            <div class="row">
                <h1 class="mx-auto">GROUP: {{ group.group_name|default:' ' }}</h1>
            </div>
            <div class="row">
                <a role="button" class="btn btn-primary"
                   href="{% url 'coffeeorder_app:menu_order_list' group.id %}"><span
                        class="glyphicon glyphicon-plus-sign"></span> CREAsssTE ORDER</a>
                <a role="button" class="btn btn-primary" href="{% url 'coffeeorder_app:add_bar' group.id %}"><span
                        class="glyphicon glyphicon-plus-sign"></span> CREATE BAR</a>
                <a role="button" class="btn btn-primary" id="inviteToGroup" onclick="show_code()"><span
                        class="glyphicon glyphicon-plus-sign"></span> INVITE TO GROUP</a>
            </div>
            <div class="row group-options">
                <a role="button" class="btn btn-danger" href="{% url 'account_app:abandon_group' group.id %}">
                    ABANDON GROUP
                </a>
                {% if admin %}
                    <a role="button" class="btn btn-danger"
                       href="{% url 'account_app:delete_group' group.id %}">ELIMINAR</a>
                    <a role="button" id="close_button" class="btn btn-warning" onclick="close_group_button()">
                        {% if group.closed %}OPEN{% else %}CLOSE{% endif %} GROUP</a>
                {% endif %}
            </div>
            <div class="row " id="invitationContainer">
                <div class="col-md-4 col-sm-12 col-md-offset-4 hidden-box">
                    <h3>INVITATION CODE:</h3>
                    <h2 style="color: red;font-weight: bold">{{ group.group_code }}</h2>
                </div>
            </div>
        {% else %}
            <p> This group does not exist anymore or you are not a member of it.</p>
        {% endif %}
    </div>

    {% include "coffeeorder_app/orderContainer.html" %}
    {% include "coffeeorder_app/memberContainer.html" %}

    {% block footer_javascript_page %}
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/coffee.js' %}"></script>
        <script>
            function close_group_button() {
                $.ajax({
                    url: "{% url 'account_app:close_group' group.id %}",

                    dataType: 'json',
                    success: function (data) {
                        if (data.is_closed) {
                            $("#close_button").text("ABRIR GRUPO")

                        } else {
                            $("#close_button").text("CERRAR GRUPO")
                        }
                    }
                });
            };
        </script>
    {% endblock footer_javascript_page %}
{% endblock %}

account_app/templates/account_app/login.html
{% extends "coffeeorder_app/base.html" %}
{% load staticfiles %}
{% block head_css_section %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet" media="screen">
{% endblock head_css_section %}
{% block title %}LOGIN{% endblock title %}
{% block content %}

    <div class="container-fluid ">
        <div class="container login-container col-md-6 col-md-offset-3">
            {% if login_error %}
                <h2 class="error_warning">{{ login_error }}</h2>
            {% endif %}
            <div class="row">
                <div class="figure col-12">
                    <svg class="figure-space" viewBox="0 0 300 300" aria-hidden="true">
                        <image class="coffee-logo" x="35%" y="25%" xlink:href="{% static 'images/svgs/1coffee.svg' %}"/>
                        <ellipse fill="#595959" cx="185" cy="270" rx="80" ry="7"/>
                        <h2>Login:</h2>
                    </svg>
                </div>
                <div class="col-md-10 col-md-offset-1">
                    <form action="{% url 'account_app:user_login' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label" for="username">Username:</label>
                            <input class="form-control" type="text" name="username" placeholder="Username">
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="password">Password:</label>
                            <input class="form-control" type="password" name="password">
                        </div>
                        <div class="text-center">
                            <input class="btn btn-primary" type="submit" name="" value="Login">
                        </div>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <h2>Registrarse:</h2>
                    <form action="{% url 'account_app:register' %}">
                        <div class=" text-center">
                            <input class="btn btn-primary" type="submit" value="SIGN UP"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

account_app/templates/account_app/registration.html
{% extends "coffeeorder_app/base.html" %}
{% load staticfiles %}
{% block head_css_section %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet" media="screen">
{% endblock head_css_section %}
{% block title %}SIGN UP{% endblock title %}
{% block content %}
    {% if registered %}
        <div class="jumbotron text-center">
            <h1>THANKS FOR SIGNING UP!</h1>
        </div>
    {% endif %}
    {% if registered == False %}
        <div class="container-fluid ">
            <div class="container-fluid registration-container col-md-6 col-md-offset-3">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <h2>SIGN UP:</h2>
                        <form enctype="multipart/form-data" method="post">
                            {% csrf_token %}
                            {% for field in user_form %}
                                <div class="form-group">
                                    <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p>{{ field.errors }}{{ forms.non_field_errors }}</p>
                                    {% if field.help_text %}
                                        <small class="form-text text-muted">{{ field.help_text }}</small>
                                    {% endif %}
                                </div>
                            {% endfor %}
                            {% for p_field in profile_form %}
                                <div class="form-group">
                                    <label class="control-label" for="{{ p_field.name }}">{{ p_field.label }}</label>
                                    {{ p_field }}
                                    <p>{{ p_field.errors }}{{ forms.non_field_errors }}</p>
                                    {% if p_field.help_text %}
                                        <small class="form-text text-muted">{{ p_field.help_text }}</small>
                                    {% endif %}
                                </div>
                            {% endfor %}
                            <div id="image-selection">
                                <div class="row">
                                </div>
                            </div>
                            <div class="text-center">
                                <input class="btn btn-primary" type="submit" name="" value="Sign up"/>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <h2>Sign in here :</h2>
                        <form action="{% url 'account_app:user_login' %}">
                            <div class="text-center">
                                <input class="btn btn-primary" type="submit" value="LOGIN"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <a class="btn btn-primary " style='margin: 5% 50%;' href="{% url 'account_app:user_login' %}">Login</a>
    {% endif %}
    <script>
        $(document).ready(function () {
            console.log("ready!");
            let image = ""
            for (i = 0; i < 17; i++) {

                image = '<img id="256_' + i + '" class="img-selection" onclick = "activate(event)" src="/static/images/profile_pics/256_' + i + '.png">';

                $('#image-selection > div.row').append(image)
            }
            $('#image-selection > div > img:nth-child(1)').addClass("img-active")
        });

        function activate(e) {
            $(".img-active").removeClass("img-active")
            $("#" + e.target.id).addClass("img-active")
            $('#id_profile_pic').val(e.target.id + '.png')
        }

    </script>
{% endblock %}